### ISSUE TITLE
INVALID JSON using sqlalchemy Datatable

### ISSUE THREAD

**Issue by kouroshh** [orf/datatables#11]
0
down vote
favorite
I am using the same template and example which exists in sqlalchemy Datatable sample in: http://sqlalchemy-datatables.readthedocs.org/en/latest/ my code is the following, my problem is invalid json, that I could not find any problems in it. any helps? The output of rowTable.output_result() is:

{'aaData': [{'1': 'DOC - 1457715381', '0': '60352794'}, {'1': 'DOC - 1457715381', '0': '2768077336'}, {'1': 'DOC - 1457715381', '0': '6247239243'}, {'1': 'DOC - 1457715381', '0': '8257884017'}, {'1': 'DOC - 1457715381', '0': '8508822379'}], 'iTotalRecords': '5', 'sEcho': '1', 'iTotalDisplayRecords': '5'}

ERROR: DataTables warning: table id=mytable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

MAKO:

`@view_config(route_name='doclist', request_method='GET', renderer='service:/templates/partials/doclist.mako', permission = 'login')
def viewListDocuments(self):
r = self.r
creator_id = 18
columns = []
columns.append(ColumnDT('doccode'))
columns.append(ColumnDT('doctitle'))
query = DBSession.query(Document).filter(Document.creator_id == creator_id)
rowTable = DataTables(r.GET, Document, query, columns)
return rowTable.output_result()`

HTML PAGE:
<table id="mytable">
            <thead>
            <tr>
                <th>
                    doccode
                </th>
                <th>
                    doctitle
                </th>                    
            </tr>
            </thead>
            <tbody>
            </tbody>

        </table>
`<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
    $('#mytable').dataTable({
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "${request.route_path('doclist')}"
    });
});`

**Comment by orf** [comment]
Hi, I think you're in the wrong place. This module is `datatables`, not `sqlalchemy-datatables`. Likely the issue is the JSON you are receiving is the "old format", whereas it's expecting the "new format" that this library produces.

No idea though. The repository you want is here: https://github.com/Pegase745/sqlalchemy-datatables

**Comment by kouroshh** [comment]
Thank you for your information.
but how could i fix this issue? any ideas?

**Comment by orf** [comment]
Hi kouroshh, your issue is with another piece of software available at this URL: https://github.com/Pegase745/sqlalchemy-datatables

Please make an issue there and describe your problem and the author will be able to respond.
